from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, 
    KeepTogether, Image
)
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.units import inch
from datetime import datetime
import os

def header_footer(canvas, doc):
    canvas.saveState()
    width, height = letter

    # Header with Foorn logo
    logo_path = "static/foorn_logo.png"  # Make sure to add your logo to static folder
    if os.path.exists(logo_path):
        canvas.drawImage(logo_path, width - 2*inch, height - inch, width=1.5*inch, height=0.75*inch)
    
    # Separator line
    canvas.setLineWidth(1)
    canvas.setStrokeColor(colors.HexColor("#22C55E"))  # Green line
    canvas.line(inch, height - 1.1*inch, width - inch, height - 1.1*inch)
    
    # Footer
    canvas.setFont("Helvetica", 10)
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(width/2, 0.75*inch, f"Page {doc.page}")
    canvas.drawString(inch, 0.75*inch, "Generated by Foorn")
    
    canvas.restoreState()

def build_common_elements(job_id, questions, report_type, candidate_info, match_score, styles):
    elements = []
    
    # Title and Generated Date
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Title'],
        fontName="Helvetica-Bold",
        fontSize=24,
        textColor=colors.black,
        alignment=TA_CENTER,
        spaceAfter=30
    )
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['BodyText'],
        fontName="Helvetica-Oblique",
        fontSize=12,
        textColor=colors.HexColor("#4B5563"),
        spaceBefore=4,
        leftIndent=20,
        leading=14,
        alignment=TA_LEFT
    )
    
    elements.append(Paragraph(f"{report_type} Interview Assessment", title_style))
    elements.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y')}", body_style))
    elements.append(Spacer(1, 20))
    
    # Match Score Section
    if match_score:
        heading_style = ParagraphStyle(
            'HeadingStyle',
            parent=styles['Heading1'],
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=colors.black,
            spaceBefore=20,
            spaceAfter=10
        )
        elements.append(Paragraph("Match Analysis", heading_style))
        elements.append(Spacer(1, 10))
        
        match_table_data = [
            [
                Paragraph(f"<b>{match_score['overall_match']}%</b><br/>Overall Match", body_style),
                Paragraph(f"<b>{match_score['skill_match']}%</b><br/>Skills Match", body_style),
                Paragraph(f"<b>{match_score['experience_match']}%</b><br/>Experience Match", body_style)
            ]
        ]
        match_table = Table(match_table_data, colWidths=[2 * inch] * 3, hAlign='CENTER')
        match_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey)
        ]))
        elements.append(match_table)
        elements.append(Spacer(1, 20))
    
    # Candidate Information Section
    if candidate_info:
        heading_style = ParagraphStyle(
            'HeadingStyle',
            parent=styles['Heading1'],
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=colors.black,
            spaceBefore=20,
            spaceAfter=10
        )
        elements.append(Paragraph("Candidate Information", heading_style))
        elements.append(Spacer(1, 10))
        
        candidate_details = [
            f"Name: {candidate_info.get('candidate_name', 'N/A')}",
            f"Email: {candidate_info.get('contact_info', {}).get('email', 'N/A')}",
            f"Phone: {candidate_info.get('contact_info', {}).get('phone', 'N/A')}",
            f"Experience: {candidate_info.get('experience_years', 'N/A')} years",
            f"Skills: {', '.join(candidate_info.get('skills', []))}"
        ]
        
        elements.append(Paragraph("<br/>".join(candidate_details), body_style))
        elements.append(Spacer(1, 20))
    
    return elements

def create_pdf_report_with_answers(job_id, questions, report_type, candidate_info, match_score, answers, output_file_path="report_with_answers.pdf"):
    """
    Generates a PDF report including both questions and their answers.
    """
    doc = SimpleDocTemplate(
        output_file_path,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )
    
    styles = getSampleStyleSheet()
    elements = build_common_elements(job_id, questions, report_type, candidate_info, match_score, styles)
    
    # Heading for Questions & Answers
    heading_style = ParagraphStyle(
        'QnAHeading',
        parent=styles['Heading1'],
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=colors.black,
        spaceBefore=20,
        spaceAfter=10,
        alignment=TA_LEFT
    )
    elements.append(Paragraph("Interview Questions & Answers", heading_style))
    elements.append(Spacer(1, 10))
    
    # Question & Answer blocks
    question_style = ParagraphStyle(
        'QuestionStyle',
        parent=styles['BodyText'],
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=colors.HexColor("#1F2937"),
        spaceAfter=6,
        alignment=TA_LEFT
    )
    answer_style = ParagraphStyle(
        'AnswerStyle',
        parent=styles['BodyText'],
        fontName="Helvetica-Oblique",
        fontSize=12,
        textColor=colors.HexColor("#4B5563"),
        spaceBefore=4,
        leftIndent=20,
        leading=14,
        alignment=TA_LEFT
    )
    
    for i, question in enumerate(questions, 1):
        block = []
        block.append(Paragraph(f"{i}. {question}", question_style))
        if answers and i - 1 < len(answers):
            block.append(Paragraph(f"<font color='#3B82F6'>Answer:</font> {answers[i-1]}", answer_style))
        block.append(Spacer(1, 15))
        elements.append(KeepTogether(block))
    
    doc.build(elements, onFirstPage=header_footer, onLaterPages=header_footer)
    return output_file_path

def create_pdf_report_questions_only(job_id, questions, report_type, candidate_info, match_score, output_file_path="report_questions_only.pdf"):
    """
    Generates a PDF report including only the interview questions.
    """
    doc = SimpleDocTemplate(
        output_file_path,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )
    
    styles = getSampleStyleSheet()
    elements = build_common_elements(job_id, questions, report_type, candidate_info, match_score, styles)
    
    # Heading for Questions only
    heading_style = ParagraphStyle(
        'QHeading',
        parent=styles['Heading1'],
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=colors.black,
        spaceBefore=20,
        spaceAfter=10,
        alignment=TA_LEFT
    )
    elements.append(Paragraph("Interview Questions", heading_style))
    elements.append(Spacer(1, 10))
    
    # Question blocks only
    question_style = ParagraphStyle(
        'QuestionStyle',
        parent=styles['BodyText'],
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=colors.HexColor("#1F2937"),
        spaceAfter=6,
        alignment=TA_LEFT
    )
    
    for i, question in enumerate(questions, 1):
        block = []
        block.append(Paragraph(f"{i}. {question}", question_style))
        block.append(Spacer(1, 15))
        elements.append(KeepTogether(block))
    
    doc.build(elements, onFirstPage=header_footer, onLaterPages=header_footer)
    return output_file_path

def create_pdf_report(job_id, questions, report_type, candidate_info=None, match_score=None, answers=None, output_file_path=None):
    """
    Main function to create the PDF report.
    If 'answers' is provided, generates a report with both questions and answers.
    Otherwise, generates a report with questions only.
    If output_file_path is not provided, a default file name is used.
    """
    if answers is not None:
        return create_pdf_report_with_answers(job_id, questions, report_type, candidate_info, match_score, answers, output_file_path)
    else:
        return create_pdf_report_questions_only(job_id, questions, report_type, candidate_info, match_score, output_file_path)

def create_nutrition_table(nutritional_data):
    """Creates a formatted table for nutritional information"""
    data = [
        ["Nutrient", "Amount per Serving"],
        ["Calories", f"{nutritional_data['calories']} kcal"],
        ["Protein", f"{nutritional_data['protein']}g"],
        ["Carbohydrates", f"{nutritional_data['carbohydrates']}g"],
        ["Fats", f"{nutritional_data['fats']}g"],
        ["Fiber", f"{nutritional_data['fiber']}g"],
        ["Sugar", f"{nutritional_data['sugar']}g"],
    ]
    
    # Add vitamins and minerals if present
    if nutritional_data.get('vitamins'):
        data.append(["Vitamins", ""])
        for vitamin, amount in nutritional_data['vitamins'].items():
            data.append([f"- {vitamin.replace('_', ' ').title()}", f"{amount}mg"])
    
    if nutritional_data.get('minerals'):
        data.append(["Minerals", ""])
        for mineral, amount in nutritional_data['minerals'].items():
            data.append([f"- {mineral.replace('_', ' ').title()}", f"{amount}mg"])

    table = Table(data, colWidths=[2.5*inch, 1.5*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#22C55E")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
    ]))
    return table

def create_dish_report(dish_analysis, output_file_path):
    """Generate a PDF report for a single dish"""
    doc = SimpleDocTemplate(
        output_file_path,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=1.2*inch,
        bottomMargin=inch
    )
    
    styles = getSampleStyleSheet()
    elements = []
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor("#22C55E"),
        spaceAfter=30
    )
    elements.append(Paragraph(dish_analysis.dish_name, title_style))
    
    # Add dish image if available
    if dish_analysis.image_url:
        try:
            img = Image(dish_analysis.image_url, width=5*inch, height=3*inch)
            elements.append(img)
            elements.append(Spacer(1, 20))
        except:
            pass
    
    # Nutritional Information Table
    elements.append(Paragraph("Nutritional Information", styles['Heading2']))
    elements.append(Spacer(1, 10))
    elements.append(create_nutrition_table(dish_analysis.nutritional_data.dict()))
    
    doc.build(elements, onFirstPage=header_footer, onLaterPages=header_footer)
    return output_file_path

def create_monthly_report(user_email: str, month: int, year: int, dishes: list, output_file_path: str):
    """Generate a monthly nutrition report"""
    doc = SimpleDocTemplate(
        output_file_path,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=1.2*inch,
        bottomMargin=inch
    )
    
    styles = getSampleStyleSheet()
    elements = []
    
    # Title
    month_name = datetime(year, month, 1).strftime("%B")
    title = f"Monthly Nutrition Report - {month_name} {year}"
    elements.append(Paragraph(title, styles['Title']))
    elements.append(Spacer(1, 20))
    
    # Summary Statistics
    total_calories = sum(dish.nutritional_data.calories for dish in dishes)
    avg_calories = total_calories / len(dishes) if dishes else 0
    
    summary_data = [
        ["Total Dishes", str(len(dishes))],
        ["Total Calories", f"{total_calories:.1f} kcal"],
        ["Average Calories/Day", f"{avg_calories:.1f} kcal"],
    ]
    
    summary_table = Table(summary_data, colWidths=[2*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F3F4F6")),
        ('GRID', (0, 0), (-1, -1), 1, colors.white),
        ('PADDING', (0, 0), (-1, -1), 12),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 30))
    
    # Daily Breakdown
    elements.append(Paragraph("Daily Nutrition Breakdown", styles['Heading2']))
    elements.append(Spacer(1, 10))
    
    for dish in dishes:
        elements.append(Paragraph(f"Dish: {dish.dish_name}", styles['Heading3']))
        elements.append(Paragraph(
            f"Date: {dish.date_analyzed.strftime('%Y-%m-%d %H:%M')}",
            styles['Normal']
        ))
        elements.append(Spacer(1, 10))
        elements.append(create_nutrition_table(dish.nutritional_data.dict()))
        elements.append(Spacer(1, 20))
    
    doc.build(elements, onFirstPage=header_footer, onLaterPages=header_footer)
    return output_file_path
